// Exact list pulled from api.frankfurter.dev/v2/currencies — 171 currencies
export const SUPPORTED_CURRENCY_CODES = new Set([
  "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN",
  "BAM", "BBD", "BDT", "BHD", "BIF", "BMD", "BND", "BOB", "BRL", "BSD",
  "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHF", "CLP", "CNH", "CNY",
  "COP", "CRC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP",
  "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GGP", "GHS", "GIP",
  "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS",
  "IMP", "INR", "IQD", "IRR", "ISK", "JEP", "JMD", "JOD", "JPY", "KES",
  "KGS", "KHR", "KMF", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR",
  "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP",
  "MRO", "MRU", "MUR", "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN",
  "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR",
  "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR",
  "SDG", "SEK", "SGD", "SHP", "SLE", "SOS", "SRD", "SSP", "STN", "SVC",
  "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD",
  "TZS", "UAH", "UGX", "USD", "UYU", "UZS", "VES", "VND", "VUV", "WST",
  "XAF", "XAG", "XAU", "XCD", "XCG", "XDR", "XOF", "XPD", "XPF", "XPT",
  "YER", "ZAR", "ZMW", "ZWG",
]);

// Fallback used only when live /v2/currencies call fails
export const FALLBACK_SUPPORTED_CURRENCIES = [
  "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN",
  "BAM", "BBD", "BDT", "BHD", "BIF", "BMD", "BND", "BOB", "BRL", "BSD",
  "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHF", "CLP", "CNH", "CNY",
  "COP", "CRC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP",
  "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GGP", "GHS", "GIP",
  "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS",
  "IMP", "INR", "IQD", "IRR", "ISK", "JEP", "JMD", "JOD", "JPY", "KES",
  "KGS", "KHR", "KMF", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR",
  "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP",
  "MRO", "MRU", "MUR", "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN",
  "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR",
  "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR",
  "SDG", "SEK", "SGD", "SHP", "SLE", "SOS", "SRD", "SSP", "STN", "SVC",
  "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD",
  "TZS", "UAH", "UGX", "USD", "UYU", "UZS", "VES", "VND", "VUV", "WST",
  "XAF", "XAG", "XAU", "XCD", "XCG", "XDR", "XOF", "XPD", "XPF", "XPT",
  "YER", "ZAR", "ZMW", "ZWG",
];

export const CURRENCY_METADATA: Record<string, { name: string; symbol: string }> = {
  AED: { name: "UAE Dirham", symbol: "د.إ" },
  AFN: { name: "Afghan Afghani", symbol: "؋" },
  ALL: { name: "Albanian Lek", symbol: "L" },
  AMD: { name: "Armenian Dram", symbol: "֏" },
  ANG: { name: "Netherlands Antillean Gulden", symbol: "ƒ" },
  AOA: { name: "Angolan Kwanza", symbol: "Kz" },
  ARS: { name: "Argentine Peso", symbol: "$" },
  AUD: { name: "Australian Dollar", symbol: "A$" },
  AWG: { name: "Aruban Florin", symbol: "ƒ" },
  AZN: { name: "Azerbaijani Manat", symbol: "₼" },
  BAM: { name: "Bosnia-Herzegovina Mark", symbol: "КМ" },
  BBD: { name: "Barbadian Dollar", symbol: "$" },
  BDT: { name: "Bangladeshi Taka", symbol: "৳" },
  BHD: { name: "Bahraini Dinar", symbol: "د.ب" },
  BIF: { name: "Burundian Franc", symbol: "Fr" },
  BMD: { name: "Bermudian Dollar", symbol: "$" },
  BND: { name: "Brunei Dollar", symbol: "$" },
  BOB: { name: "Bolivian Boliviano", symbol: "Bs." },
  BRL: { name: "Brazilian Real", symbol: "R$" },
  BSD: { name: "Bahamian Dollar", symbol: "$" },
  BTN: { name: "Bhutanese Ngultrum", symbol: "Nu." },
  BWP: { name: "Botswana Pula", symbol: "P" },
  BYN: { name: "Belarusian Ruble", symbol: "Br" },
  BZD: { name: "Belize Dollar", symbol: "$" },
  CAD: { name: "Canadian Dollar", symbol: "CA$" },
  CDF: { name: "Congolese Franc", symbol: "Fr" },
  CHF: { name: "Swiss Franc", symbol: "CHF" },
  CLP: { name: "Chilean Peso", symbol: "$" },
  CNH: { name: "Chinese Yuan Offshore", symbol: "¥" },
  CNY: { name: "Chinese Yuan", symbol: "CN¥" },
  COP: { name: "Colombian Peso", symbol: "$" },
  CRC: { name: "Costa Rican Colón", symbol: "₡" },
  CUP: { name: "Cuban Peso", symbol: "$" },
  CVE: { name: "Cape Verdean Escudo", symbol: "$" },
  CZK: { name: "Czech Koruna", symbol: "Kč" },
  DJF: { name: "Djiboutian Franc", symbol: "Fdj" },
  DKK: { name: "Danish Krone", symbol: "kr." },
  DOP: { name: "Dominican Peso", symbol: "$" },
  DZD: { name: "Algerian Dinar", symbol: "د.ج" },
  EGP: { name: "Egyptian Pound", symbol: "E£" },
  ERN: { name: "Eritrean Nakfa", symbol: "Nfk" },
  ETB: { name: "Ethiopian Birr", symbol: "Br" },
  EUR: { name: "Euro", symbol: "€" },
  FJD: { name: "Fijian Dollar", symbol: "$" },
  FKP: { name: "Falkland Pound", symbol: "£" },
  GBP: { name: "British Pound", symbol: "£" },
  GEL: { name: "Georgian Lari", symbol: "₾" },
  GGP: { name: "Guernsey Pound", symbol: "£" },
  GHS: { name: "Ghanaian Cedi", symbol: "₵" },
  GIP: { name: "Gibraltar Pound", symbol: "£" },
  GMD: { name: "Gambian Dalasi", symbol: "D" },
  GNF: { name: "Guinean Franc", symbol: "Fr" },
  GTQ: { name: "Guatemalan Quetzal", symbol: "Q" },
  GYD: { name: "Guyanese Dollar", symbol: "$" },
  HKD: { name: "Hong Kong Dollar", symbol: "HK$" },
  HNL: { name: "Honduran Lempira", symbol: "L" },
  HTG: { name: "Haitian Gourde", symbol: "G" },
  HUF: { name: "Hungarian Forint", symbol: "Ft" },
  IDR: { name: "Indonesian Rupiah", symbol: "Rp" },
  ILS: { name: "Israeli Shekel", symbol: "₪" },
  IMP: { name: "Isle of Man Pound", symbol: "£" },
  INR: { name: "Indian Rupee", symbol: "₹" },
  IQD: { name: "Iraqi Dinar", symbol: "ع.د" },
  IRR: { name: "Iranian Rial", symbol: "﷼" },
  ISK: { name: "Icelandic Króna", symbol: "kr." },
  JEP: { name: "Jersey Pound", symbol: "£" },
  JMD: { name: "Jamaican Dollar", symbol: "$" },
  JOD: { name: "Jordanian Dinar", symbol: "د.ا" },
  JPY: { name: "Japanese Yen", symbol: "¥" },
  KES: { name: "Kenyan Shilling", symbol: "KSh" },
  KGS: { name: "Kyrgyzstani Som", symbol: "som" },
  KHR: { name: "Cambodian Riel", symbol: "៛" },
  KMF: { name: "Comorian Franc", symbol: "Fr" },
  KRW: { name: "South Korean Won", symbol: "₩" },
  KWD: { name: "Kuwaiti Dinar", symbol: "د.ك" },
  KYD: { name: "Cayman Islands Dollar", symbol: "$" },
  KZT: { name: "Kazakhstani Tenge", symbol: "₸" },
  LAK: { name: "Lao Kip", symbol: "₭" },
  LBP: { name: "Lebanese Pound", symbol: "ل.ل" },
  LKR: { name: "Sri Lankan Rupee", symbol: "₨" },
  LRD: { name: "Liberian Dollar", symbol: "$" },
  LSL: { name: "Lesotho Loti", symbol: "L" },
  LYD: { name: "Libyan Dinar", symbol: "ل.د" },
  MAD: { name: "Moroccan Dirham", symbol: "د.م." },
  MDL: { name: "Moldovan Leu", symbol: "L" },
  MGA: { name: "Malagasy Ariary", symbol: "Ar" },
  MKD: { name: "Macedonian Denar", symbol: "ден" },
  MMK: { name: "Myanmar Kyat", symbol: "K" },
  MNT: { name: "Mongolian Tögrög", symbol: "₮" },
  MOP: { name: "Macanese Pataca", symbol: "P" },
  MRO: { name: "Mauritanian Ouguiya (old)", symbol: "UM" },
  MRU: { name: "Mauritanian Ouguiya", symbol: "UM" },
  MUR: { name: "Mauritian Rupee", symbol: "₨" },
  MVR: { name: "Maldivian Rufiyaa", symbol: "MVR" },
  MWK: { name: "Malawian Kwacha", symbol: "MK" },
  MXN: { name: "Mexican Peso", symbol: "MX$" },
  MYR: { name: "Malaysian Ringgit", symbol: "RM" },
  MZN: { name: "Mozambican Metical", symbol: "MTn" },
  NAD: { name: "Namibian Dollar", symbol: "$" },
  NGN: { name: "Nigerian Naira", symbol: "₦" },
  NIO: { name: "Nicaraguan Córdoba", symbol: "C$" },
  NOK: { name: "Norwegian Krone", symbol: "kr" },
  NPR: { name: "Nepalese Rupee", symbol: "Rs." },
  NZD: { name: "New Zealand Dollar", symbol: "NZ$" },
  OMR: { name: "Omani Rial", symbol: "ر.ع." },
  PAB: { name: "Panamanian Balboa", symbol: "B/." },
  PEN: { name: "Peruvian Sol", symbol: "S/" },
  PGK: { name: "Papua New Guinean Kina", symbol: "K" },
  PHP: { name: "Philippine Peso", symbol: "₱" },
  PKR: { name: "Pakistani Rupee", symbol: "₨" },
  PLN: { name: "Polish Złoty", symbol: "zł" },
  PYG: { name: "Paraguayan Guaraní", symbol: "₲" },
  QAR: { name: "Qatari Riyal", symbol: "ر.ق" },
  RON: { name: "Romanian Leu", symbol: "Lei" },
  RSD: { name: "Serbian Dinar", symbol: "RSD" },
  RUB: { name: "Russian Ruble", symbol: "₽" },
  RWF: { name: "Rwandan Franc", symbol: "FRw" },
  SAR: { name: "Saudi Riyal", symbol: "ر.س" },
  SBD: { name: "Solomon Islands Dollar", symbol: "$" },
  SCR: { name: "Seychellois Rupee", symbol: "₨" },
  SDG: { name: "Sudanese Pound", symbol: "£" },
  SEK: { name: "Swedish Krona", symbol: "kr" },
  SGD: { name: "Singapore Dollar", symbol: "S$" },
  SHP: { name: "Saint Helenian Pound", symbol: "£" },
  SLE: { name: "New Leone", symbol: "Le" },
  SOS: { name: "Somali Shilling", symbol: "Sh" },
  SRD: { name: "Surinamese Dollar", symbol: "$" },
  SSP: { name: "South Sudanese Pound", symbol: "£" },
  STN: { name: "São Tomé Dobra", symbol: "Db" },
  SVC: { name: "Salvadoran Colón", symbol: "₡" },
  SYP: { name: "Syrian Pound", symbol: "£S" },
  SZL: { name: "Swazi Lilangeni", symbol: "E" },
  THB: { name: "Thai Baht", symbol: "฿" },
  TJS: { name: "Tajikistani Somoni", symbol: "ЅМ" },
  TMT: { name: "Turkmenistani Manat", symbol: "m" },
  TND: { name: "Tunisian Dinar", symbol: "د.ت" },
  TOP: { name: "Tongan Paʻanga", symbol: "T$" },
  TRY: { name: "Turkish Lira", symbol: "₺" },
  TTD: { name: "Trinidad & Tobago Dollar", symbol: "$" },
  TWD: { name: "New Taiwan Dollar", symbol: "NT$" },
  TZS: { name: "Tanzanian Shilling", symbol: "Sh" },
  UAH: { name: "Ukrainian Hryvnia", symbol: "₴" },
  UGX: { name: "Ugandan Shilling", symbol: "USh" },
  USD: { name: "US Dollar", symbol: "$" },
  UYU: { name: "Uruguayan Peso", symbol: "$U" },
  UZS: { name: "Uzbekistan Som", symbol: "so'm" },
  VES: { name: "Venezuelan Bolívar", symbol: "Bs" },
  VND: { name: "Vietnamese Đồng", symbol: "₫" },
  VUV: { name: "Vanuatu Vatu", symbol: "Vt" },
  WST: { name: "Samoan Tala", symbol: "T" },
  XAF: { name: "Central African CFA Franc", symbol: "CFA" },
  XAG: { name: "Silver (Troy Ounce)", symbol: "oz t" },
  XAU: { name: "Gold (Troy Ounce)", symbol: "oz t" },
  XCD: { name: "East Caribbean Dollar", symbol: "$" },
  XCG: { name: "Caribbean Guilder", symbol: "Cg" },
  XDR: { name: "Special Drawing Rights", symbol: "SDR" },
  XOF: { name: "West African CFA Franc", symbol: "Fr" },
  XPD: { name: "Palladium", symbol: "oz t" },
  XPF: { name: "CFP Franc", symbol: "Fr" },
  XPT: { name: "Platinum", symbol: "oz t" },
  YER: { name: "Yemeni Rial", symbol: "﷼" },
  ZAR: { name: "South African Rand", symbol: "R" },
  ZMW: { name: "Zambian Kwacha", symbol: "K" },
  ZWG: { name: "Zimbabwe Gold", symbol: "ZiG" },
};

export const isValidCurrencyCode = (code: string): boolean =>
  SUPPORTED_CURRENCY_CODES.has(code.toUpperCase());